## Pandas Data Frames

- What Is Pandas?
- Pandas vs Numpy 
- Pandas Data Frame Intro
- Pandas Data Frame fundamental operations
    - Creating
    - Selecting/indexing
    - Inserting rows/columns
    - Setting data
    - Filtering
    - dropping rwos/ columns
- Dealing with Missing values

%matplotlib inline
import numpy as np
import pandas as pd
from IPython.display import Image
from IPython.display import HTML
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))


CSS = """
.output {
    align-items: center;
}
"""
HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Code mode"></form>''')

In [57]:
from IPython.display import display,Image, HTML

CSS = """
.output {
    align-items: center;
}
div.output_area {
    width: 80%;
}
"""
HTML('<style>{}</style>'.format(CSS))

# What is Pandas?

### - Enables working with tabular and labeled data easily and intuitively
### - Pandas is an open-source library built on top of Numpy Package.
- https://github.com/pandas-dev/pandas
- https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/pandas/core/frame.py

### - Pandas data structures are:
    - Series
    - Index
    - Data Frame
    

## Quick refresh to Numpy Arrays..
- contains Numerical ***Homogonius*** Data
- may contain multi dimensional array elements.
- used for performing various numerical computations and processing of the multidimensional and single-dimensional array elements.

In [58]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

two_dim_arr = np.random.randint(10, size=(3, 4))  # Two-dimensional array
three_dim_arr = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


In [59]:
np.random.randint(10, size=(3, 4))  

array([[5, 9, 4, 4],
       [6, 4, 4, 3],
       [4, 4, 8, 4]])

In [60]:
np.random.randint(10, size=(3, 4, 5))

array([[[3, 7, 5, 5, 0],
        [1, 5, 9, 3, 0],
        [5, 0, 1, 2, 4],
        [2, 0, 3, 2, 0]],

       [[7, 5, 9, 0, 2],
        [7, 2, 9, 2, 3],
        [3, 2, 3, 4, 1],
        [2, 9, 1, 4, 6]],

       [[8, 2, 3, 0, 0],
        [6, 0, 6, 3, 3],
        [8, 8, 8, 2, 3],
        [2, 0, 8, 8, 3]]])

### A two dimensional Array example...

In [61]:
print("Two Dimentional Array")
two_dim_arr

Two Dimentional Array


array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

### What I mean by Homogeneous...

In [62]:
print(two_dim_arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


**two_dim_arr[0,0] = "Hello"**

In [63]:
#printmd("***Oops....***")
two_dim_arr[0,0] = "Hello" 

ValueError: invalid literal for int() with base 10: 'Hello'

### You can directly and simply form the DataFrame from the 2D array

In [64]:
import pandas as pd

In [65]:

print("Data Frame formed by 2D Array")
#printmd("***df=pd.DataFrame(two_dim_arr)***")
df=pd.DataFrame(two_dim_arr)
df

Data Frame formed by 2D Array


0  1  2  3
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6

### Pandas Data Frame is Heterogeneous!
**df.iloc[0,0]="Hello"**

In [66]:
df.iloc[0,0]="Hello"
df

0  1  2  3
0  Hello  0  3  3
1      7  9  3  5
2      2  4  7  6

### Pandas Data Frame labels the data with Indices and Columns labels
pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

In [67]:
np.random.randint(10,size=(3,2))

array([[8, 2],
       [8, 4],
       [3, 0]])

In [68]:
##np.random.seed(0)
foo_df=pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c']
                   )

In [69]:
foo_df

foo  bar
a    4    3
b    6    9
c    8    0

In [70]:
foo_df

foo  bar
a    4    3
b    6    9
c    8    0

### Pandas DataFrame is relevant for statistical observations/data points with various variables (categorical, etc) 

In [71]:
Image("res/Tidy_census.png")

FileNotFoundError: No such file or directory: 'res/Tidy_census.png'

FileNotFoundError: No such file or directory: 'res/Tidy_census.png'

<IPython.core.display.Image object>

### It is intuitive...  Look how convenient it is!!

In [72]:
people_df= pd.read_csv("data/people.csv")
people_df

FileNotFoundError: [Errno 2] No such file or directory: 'data/people.csv'

In [73]:
Image('res/excel-to-pandas.png')

FileNotFoundError: No such file or directory: 'res/excel-to-pandas.png'

FileNotFoundError: No such file or directory: 'res/excel-to-pandas.png'

<IPython.core.display.Image object>

source: https://jalammar.github.io/

### Describing the Data Frame...
- df.Info()
- df.count())
- df.describe())
- df.mean())

In [74]:
people_df

NameError: name 'people_df' is not defined

In [75]:
people_df.info()

NameError: name 'people_df' is not defined

In [76]:
people_df.describe()

NameError: name 'people_df' is not defined

In [77]:
people_df["age"].describe()

NameError: name 'people_df' is not defined

In [78]:
people_df.count()

NameError: name 'people_df' is not defined

In [79]:
x=[1,3,4,50]
print(np.median(x))
print(np.mean(x))

3.5
14.5


In [80]:
#print(df,"\n")
people_df.info()
#print("df.count()  \n",df.count())
#print("\n df.describe() \n",df.describe())
#print("\n df.mean() \n",df.mean())

NameError: name 'people_df' is not defined

### Pandas Data Frame operations

In [81]:
Image("res/CRUD.png")

FileNotFoundError: No such file or directory: 'res/CRUD.png'

FileNotFoundError: No such file or directory: 'res/CRUD.png'

<IPython.core.display.Image object>

### Data Frame creation
You can create/form a Data Frame from:
- Dict of 1D ndarrays, lists, dicts, or Series

- 2-D numpy.ndarray

- Structured or record ndarray

- A Series

- Another DataFrame

#### Here is an example...

In [82]:
print('dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}\n')

dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}

dic

dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}



{'col1': [1.0, 2.0, 3.0, 4.0], 'col2': [4.0, 3.0, 2.0, 1.0]}

In [83]:
df=pd.DataFrame(dic)

#### creating Index for the Data frame...

In [84]:
df=pd.DataFrame(dic,index=["a", "b", "c", "d"])
df

col1  col2
a   1.0   4.0
b   2.0   3.0
c   3.0   2.0
d   4.0   1.0

In [85]:
np.array(df["col1"])

array([1., 2., 3., 4.])

### Creating Data frame from Pandas Series objects.. 

In [86]:
d = {
       "apples": [3, 2, 0,1],
        "oranges": [0, 3, 7, 2],
    }

pd.DataFrame(d)

apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [87]:
Image("res/series-and-dataframe.width-1200.png")

FileNotFoundError: No such file or directory: 'res/series-and-dataframe.width-1200.png'

FileNotFoundError: No such file or directory: 'res/series-and-dataframe.width-1200.png'

<IPython.core.display.Image object>

source: https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png

### Data Frame Selection / Indexing

In [88]:
data = {
    'name': ['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
    'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai',
             'Manchester', 'Cairo', 'Osaka'],
    'age': [41, 28, 33, 34, 38, 31, 37],
    'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}

row_labels = [101, 102, 103, 104, 105, 106, 107]
students_df = pd.DataFrame(data=data, index=row_labels)
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [89]:
students_df.index

Int64Index([101, 102, 103, 104, 105, 106, 107], dtype='int64')

Source: https://realpython.com/

### data Selection

In [90]:
students_df.loc[[101],["age"]]

age
101   41

In [91]:
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

### Selecting by Label
- .loc[]  function

In [92]:
#print("students_df.loc[:, 'city']")
#students_df.loc[:, 'city']

In [93]:
print("students_df.loc[102:106, ['name', 'city']]")
students_df.loc[102,:]

students_df.loc[102:106, ['name', 'city']]


name            Ann
city        Toronto
age              28
py-score       79.0
Name: 102, dtype: object

In [94]:
#print('df["city"]')
cities = students_df[["age","city"]]
cities

age         city
101   41  Mexico City
102   28      Toronto
103   33       Prague
104   34     Shanghai
105   38   Manchester
106   31        Cairo
107   37        Osaka

In [95]:
print("df.city")
students_df.city

df.city


101    Mexico City
102        Toronto
103         Prague
104       Shanghai
105     Manchester
106          Cairo
107          Osaka
Name: city, dtype: object

### Selecting by Position
- .iloc[]

In [96]:
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [97]:
students_df.iloc[0,1]

'Mexico City'

In [98]:
print("students_df.iloc[1:6, [0, 1]]")
students_df.iloc[1:6, [0, 1]]

students_df.iloc[1:6, [0, 1]]


name        city
102    Ann     Toronto
103   Jana      Prague
104     Yi    Shanghai
105  Robin  Manchester
106   Amal       Cairo

### Hmm.. Can you tell what is the difference between loc and iloc?

### Setting/ Updating data

#### let us first update the Data frame index..

In [99]:
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [100]:
students_df.index = list(np.arange(0, 7))
students_df

name         city  age  py-score
0  Xavier  Mexico City   41      88.0
1     Ann      Toronto   28      79.0
2    Jana       Prague   33      81.0
3      Yi     Shanghai   34      80.0
4   Robin   Manchester   38      68.0
5    Amal        Cairo   31      61.0
6    Nori        Osaka   37      84.0

In [101]:
students_df=students_df.reset_index()

In [102]:
students_df.index

RangeIndex(start=0, stop=7, step=1)

In [103]:
students_df.iloc[:4, 4] = [40, 50, 60, 70]
students_df

index    name         city  age  py-score
0      0  Xavier  Mexico City   41      40.0
1      1     Ann      Toronto   28      50.0
2      2    Jana       Prague   33      60.0
3      3      Yi     Shanghai   34      70.0
4      4   Robin   Manchester   38      68.0
5      5    Amal        Cairo   31      61.0
6      6    Nori        Osaka   37      84.0

In [104]:
students_df.loc[5, 'py-score'] 

61.0

In [105]:
students_df.loc[5, 'py-score'] = 70
students_df

index    name         city  age  py-score
0      0  Xavier  Mexico City   41      40.0
1      1     Ann      Toronto   28      50.0
2      2    Jana       Prague   33      60.0
3      3      Yi     Shanghai   34      70.0
4      4   Robin   Manchester   38      68.0
5      5    Amal        Cairo   31      70.0
6      6    Nori        Osaka   37      84.0

In [106]:
students_df.loc[:,"py-score"]=90 
students_df

index    name         city  age  py-score
0      0  Xavier  Mexico City   41        90
1      1     Ann      Toronto   28        90
2      2    Jana       Prague   33        90
3      3      Yi     Shanghai   34        90
4      4   Robin   Manchester   38        90
5      5    Amal        Cairo   31        90
6      6    Nori        Osaka   37        90

In [107]:
students_df.iloc[:, -1] = [88.0, 90, 81.0, 80.0, 68.0, 61.0, 84.0]
students_df

index    name         city  age  py-score
0      0  Xavier  Mexico City   41      88.0
1      1     Ann      Toronto   28      90.0
2      2    Jana       Prague   33      81.0
3      3      Yi     Shanghai   34      80.0
4      4   Robin   Manchester   38      68.0
5      5    Amal        Cairo   31      61.0
6      6    Nori        Osaka   37      84.0

In [108]:
students_df["py-score"]="Adam-score"
students_df

index    name         city  age    py-score
0      0  Xavier  Mexico City   41  Adam-score
1      1     Ann      Toronto   28  Adam-score
2      2    Jana       Prague   33  Adam-score
3      3      Yi     Shanghai   34  Adam-score
4      4   Robin   Manchester   38  Adam-score
5      5    Amal        Cairo   31  Adam-score
6      6    Nori        Osaka   37  Adam-score

In [109]:
students_df

index    name         city  age    py-score
0      0  Xavier  Mexico City   41  Adam-score
1      1     Ann      Toronto   28  Adam-score
2      2    Jana       Prague   33  Adam-score
3      3      Yi     Shanghai   34  Adam-score
4      4   Robin   Manchester   38  Adam-score
5      5    Amal        Cairo   31  Adam-score
6      6    Nori        Osaka   37  Adam-score

In [110]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   index     7 non-null      int64 
 1   name      7 non-null      object
 2   city      7 non-null      object
 3   age       7 non-null      int64 
 4   py-score  7 non-null      object
dtypes: int64(2), object(3)
memory usage: 408.0+ bytes


In [111]:
students_df["py-score"]=students_df["py-score"]  * 1.5

TypeError: can't multiply sequence by non-int of type 'float'

In [112]:
students_df

index    name         city  age    py-score
0      0  Xavier  Mexico City   41  Adam-score
1      1     Ann      Toronto   28  Adam-score
2      2    Jana       Prague   33  Adam-score
3      3      Yi     Shanghai   34  Adam-score
4      4   Robin   Manchester   38  Adam-score
5      5    Amal        Cairo   31  Adam-score
6      6    Nori        Osaka   37  Adam-score

In [113]:
students_df["py-score"]=list(map(lambda x: x+10,students_df["py-score"]))

TypeError: can only concatenate str (not "int") to str

In [114]:
students_df["py-score"] +=  10


TypeError: can only concatenate str (not "int") to str

In [115]:
students_df

index    name         city  age    py-score
0      0  Xavier  Mexico City   41  Adam-score
1      1     Ann      Toronto   28  Adam-score
2      2    Jana       Prague   33  Adam-score
3      3      Yi     Shanghai   34  Adam-score
4      4   Robin   Manchester   38  Adam-score
5      5    Amal        Cairo   31  Adam-score
6      6    Nori        Osaka   37  Adam-score

In [116]:
students_df["py-score"]= students_df["py-score"] + students_df["age"]

TypeError: can only concatenate str (not "int") to str

In [117]:
students_df

index    name         city  age    py-score
0      0  Xavier  Mexico City   41  Adam-score
1      1     Ann      Toronto   28  Adam-score
2      2    Jana       Prague   33  Adam-score
3      3      Yi     Shanghai   34  Adam-score
4      4   Robin   Manchester   38  Adam-score
5      5    Amal        Cairo   31  Adam-score
6      6    Nori        Osaka   37  Adam-score

In [118]:
students_df.columns = ['index', 'name', 'city', 'age', 'py-score']

In [119]:
students_df

index    name         city  age    py-score
0      0  Xavier  Mexico City   41  Adam-score
1      1     Ann      Toronto   28  Adam-score
2      2    Jana       Prague   33  Adam-score
3      3      Yi     Shanghai   34  Adam-score
4      4   Robin   Manchester   38  Adam-score
5      5    Amal        Cairo   31  Adam-score
6      6    Nori        Osaka   37  Adam-score

In [120]:
students_df[["age","py-score"]]

age    py-score
0   41  Adam-score
1   28  Adam-score
2   33  Adam-score
3   34  Adam-score
4   38  Adam-score
5   31  Adam-score
6   37  Adam-score

In [121]:
type(students_df[["age"]])

pandas.core.frame.DataFrame

### Inserting/deleteing rows

In [122]:
students_df.columns


Index(['index', 'name', 'city', 'age', 'py-score'], dtype='object')

In [123]:
students_df  = students_df[['name', 'city', 'age', 'py-score']]
students_df

name         city  age    py-score
0  Xavier  Mexico City   41  Adam-score
1     Ann      Toronto   28  Adam-score
2    Jana       Prague   33  Adam-score
3      Yi     Shanghai   34  Adam-score
4   Robin   Manchester   38  Adam-score
5    Amal        Cairo   31  Adam-score
6    Nori        Osaka   37  Adam-score

In [124]:
Ronald = pd.Series(data=['Ronald', 'Berlin', 34, 79],
                 index=students_df.columns[0:4])
students_df= students_df.append(Ronald,ignore_index=True)
students_df

/var/folders/d0/kyjzvmwn3fdgc5m0t8snt0nm0000gn/T/ipykernel_80589/2686564188.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  students_df= students_df.append(Ronald,ignore_index=True)


name         city  age    py-score
0  Xavier  Mexico City   41  Adam-score
1     Ann      Toronto   28  Adam-score
2    Jana       Prague   33  Adam-score
3      Yi     Shanghai   34  Adam-score
4   Robin   Manchester   38  Adam-score
5    Amal        Cairo   31  Adam-score
6    Nori        Osaka   37  Adam-score
7  Ronald       Berlin   34          79

In [125]:
students_df.iloc[7,:]

name        Ronald
city        Berlin
age             34
py-score        79
Name: 7, dtype: object

In [126]:
Ronald = pd.Series(data=['Ronald', 'Berlin', 34, 79],
                 index=students_df.columns[0:4],name=21)

In [127]:
students_df=students_df.append(Ronald)


/var/folders/d0/kyjzvmwn3fdgc5m0t8snt0nm0000gn/T/ipykernel_80589/604143898.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  students_df=students_df.append(Ronald)


In [128]:
students_df

name         city  age    py-score
0   Xavier  Mexico City   41  Adam-score
1      Ann      Toronto   28  Adam-score
2     Jana       Prague   33  Adam-score
3       Yi     Shanghai   34  Adam-score
4    Robin   Manchester   38  Adam-score
5     Amal        Cairo   31  Adam-score
6     Nori        Osaka   37  Adam-score
7   Ronald       Berlin   34          79
21  Ronald       Berlin   34          79

In [129]:
students_df.drop(labels=[7],inplace=True)

In [172]:
students_df

name         city  age  py-score
0  Xavier  Mexico City   41     213.0
1     Ann      Toronto   28     203.0
2    Jana       Prague   33     194.5
3      Yi     Shanghai   34     194.0
4   Robin   Manchester   38     180.0
5    Amal        Cairo   31     162.5
6    Nori        Osaka   37     203.0

### Inserting/Deleting columns

In [173]:
#print('df[js-score] = np.array([71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80.0])')
students_df['js-score'] =[71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80.0]
students_df

name         city  age  py-score  js-score
0  Xavier  Mexico City   41     213.0      71.0
1     Ann      Toronto   28     203.0      95.0
2    Jana       Prague   33     194.5      88.0
3      Yi     Shanghai   34     194.0      79.0
4   Robin   Manchester   38     180.0      91.0
5    Amal        Cairo   31     162.5      91.0
6    Nori        Osaka   37     203.0      80.0

In [175]:
students_df['py-score-updated'] = students_df['py-score'] * 10 

In [176]:
students_df

name         city  age  py-score  django-score  js-score  \
0  Xavier  Mexico City   41     213.0          70.0      71.0   
1     Ann      Toronto   28     203.0          74.0      95.0   
2    Jana       Prague   33     194.5          78.0      88.0   
3      Yi     Shanghai   34     194.0          56.0      79.0   
4   Robin   Manchester   38     180.0          66.0      91.0   
5    Amal        Cairo   31     162.5          78.0      91.0   
6    Nori        Osaka   37     203.0          81.0      80.0   

   py-score-updated  
0            2130.0  
1            2030.0  
2            1945.0  
3            1940.0  
4            1800.0  
5            1625.0  
6            2030.0

### Inserting in a specific location

In [174]:
#print('df.insert(loc=4, column=js-score,value=np.array([86.0, 81.0, 78.0, 88.0, 74.0, 70.0, 81.0]))')
students_df.insert(loc=4, column='django-score',
          value=np.array([70, 74, 78, 56, 66, 78, 81.0]))
students_df

name         city  age  py-score  django-score  js-score
0  Xavier  Mexico City   41     213.0          70.0      71.0
1     Ann      Toronto   28     203.0          74.0      95.0
2    Jana       Prague   33     194.5          78.0      88.0
3      Yi     Shanghai   34     194.0          56.0      79.0
4   Robin   Manchester   38     180.0          66.0      91.0
5    Amal        Cairo   31     162.5          78.0      91.0
6    Nori        Osaka   37     203.0          81.0      80.0

### dropping specific column

In [177]:

## axis= 0 dropping by row,  axis=1. ropping by column
students_df = students_df.drop(labels=['django-score'], axis=1)

In [178]:
students_df

name         city  age  py-score  js-score  py-score-updated
0  Xavier  Mexico City   41     213.0      71.0            2130.0
1     Ann      Toronto   28     203.0      95.0            2030.0
2    Jana       Prague   33     194.5      88.0            1945.0
3      Yi     Shanghai   34     194.0      79.0            1940.0
4   Robin   Manchester   38     180.0      91.0            1800.0
5    Amal        Cairo   31     162.5      91.0            1625.0
6    Nori        Osaka   37     203.0      80.0            2030.0

### Filtering/Boolean Indexing

In [182]:
students_df["py-score"] >= 200

0     True
1     True
2    False
3    False
4    False
5    False
6     True
Name: py-score, dtype: bool

In [180]:
students_df[students_df["py-score"]>=200]

name         city  age  py-score  js-score  py-score-updated
0  Xavier  Mexico City   41     213.0      71.0            2130.0
1     Ann      Toronto   28     203.0      95.0            2030.0
6    Nori        Osaka   37     203.0      80.0            2030.0

In [183]:
very_good_students_filter = students_df['py-score'] >= 200
very_good_students_filter

0     True
1     True
2    False
3    False
4    False
5    False
6     True
Name: py-score, dtype: bool

In [184]:
students_df[very_good_students_filter]

name         city  age  py-score  js-score  py-score-updated
0  Xavier  Mexico City   41     213.0      71.0            2130.0
1     Ann      Toronto   28     203.0      95.0            2030.0
6    Nori        Osaka   37     203.0      80.0            2030.0

### Creating powerful filters with Logical operators AND, OR, NOT, XOR

In [194]:
#print('df[(df[py-score] >= 80) & (df[js-score] >= 80)]')
students_df[(students_df['py-score'] >= 200) | (students_df['js-score'] >= 80)]

name         city  age  py-score  js-score  py-score-updated
0  Xavier  Mexico City   41     213.0      71.0            2130.0
1     Ann      Toronto   28     203.0      95.0            2030.0
2    Jana       Prague   33     194.5      88.0            1945.0
4   Robin   Manchester   38     180.0      91.0            1800.0
5    Amal        Cairo   31     162.5      91.0            1625.0
6    Nori        Osaka   37     203.0      80.0            2030.0

## using value counts  function

In [207]:
people_df=pd.read_csv("data/people.csv")
people_df

name  age country
0    Pol   22      ES
1   Javi   20      ES
2  Maria   23      AR
3   Anna   24      FR
4   Anna   24      UK
5   Javi   30      MA
6    Dog    2      XX

In [208]:
people_df["country"].value_counts()

ES    2
AR    1
FR    1
UK    1
MA    1
XX    1
Name: country, dtype: int64